name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ctp_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: make -C ctp test
  
  cli_build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: make cli
      run: make -C ctp cli
